# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 242b35e6ffb85f9f40c51b161d69e41fa1fceb63cd05a876faeef18b469fa79962c19ec952b84ddfeae8764b100171e7d6fb4579f488f0b6d730970a63bdbc08

test:
  secret_key_base: e0e021b1aed0d393b2ca3c649ae7e6b114c18e0ea5849eaad1ca40e8328b26afb734fc0858432d44d9321f8cdb0b3c95a491dae7b49c3736c5c162fa62f5a42a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
